/* Generated by comet rpc generate. Do not edit by hand. */

export type TokenProvider = () => string | null | undefined | Promise<string | null | undefined>;

export interface BoardRow {
  id: number;
  org_id: number;
  title: string;
}

export interface NewTask {
  title: string;
}

export interface PrivateMeResponse {
  session_id: string;
  user_id: string;
  email?: string | null;
}

export interface Task {
  id: number;
  title: string;
  done: boolean;
  created_at: string;
}

export class CometRpcError extends Error {
  readonly status: number;
  readonly body: unknown;

  constructor(status: number, body: unknown) {
    super(`Comet RPC request failed with status ${status}`);
    this.name = "CometRpcError";
    this.status = status;
    this.body = body;
  }
}

export class CometClient {
  constructor(
    private readonly baseUrl: string,
    private readonly tokenProvider?: TokenProvider,
  ) {}

  async listOrgBoards(org_id: number): Promise<Array<BoardRow>> {
    return this.request<Array<BoardRow>>("GET", `/orgs/${encodePathValue(org_id)}/boards`, undefined, true);
  }

  async privateMe(): Promise<PrivateMeResponse> {
    return this.request<PrivateMeResponse>("GET", `/private/me`, undefined, true);
  }

  async completeTask(id: number): Promise<Task> {
    return this.request<Task>("POST", `/tasks/${encodePathValue(id)}/complete`, undefined, true);
  }

  async createTask(new_task: NewTask): Promise<Task> {
    return this.request<Task>("POST", `/tasks`, new_task, true);
  }

  async getTask(id: number): Promise<Task> {
    return this.request<Task>("GET", `/tasks/${encodePathValue(id)}`, undefined, true);
  }

  async listTasks(): Promise<Array<Task>> {
    return this.request<Array<Task>>("GET", `/tasks`, undefined, true);
  }

  private async request<T>(method: string, path: string, body: unknown, auth: boolean): Promise<T> {
    const headers: Record<string, string> = { accept: "application/json" };
    let requestBody: string | undefined;
    if (body !== undefined) {
      headers["content-type"] = "application/json";
      requestBody = JSON.stringify(body);
    }
    if (auth && this.tokenProvider) {
      const token = await this.tokenProvider();
      if (token) headers.authorization = `Bearer ${token}`;
    }

    const response = await fetch(`${this.baseUrl.replace(/\/$/, "")}${path}`, {
      method,
      headers,
      body: requestBody,
    });
    const text = await response.text();
    const payload = text ? JSON.parse(text) : undefined;
    if (!response.ok) throw new CometRpcError(response.status, payload);
    return payload as T;
  }
}

function encodePathValue(value: string | number | boolean | Array<string | number | boolean>): string {
  if (Array.isArray(value)) return value.map((item) => encodeURIComponent(String(item))).join("/");
  return encodeURIComponent(String(value));
}
