use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};
use quote::ToTokens;
use serde::{Deserialize, Serialize};
use syn::parse::{Parse, ParseStream};
use syn::punctuated::Punctuated;
use syn::visit::{self, Visit};
use syn::{
    Attribute, Expr, ExprMethodCall, Field, Fields, FnArg, Item, ItemFn, Lit, LitStr, Pat,
    ReturnType, Token, Type, Visibility,
};
use toml::Value;

const MANIFEST_VERSION: u32 = 1;

#[derive(Debug, Serialize, PartialEq, Eq)]
pub struct RpcManifest {
    pub version: u32,
    pub routes: Vec<RpcRoute>,
}

#[derive(Debug, Serialize, PartialEq, Eq)]
pub struct RpcRoute {
    pub name: String,
    pub module_path: Vec<String>,
    pub source: String,
    pub method: String,
    pub path: String,
    pub data_param: Option<String>,
    pub path_params: Vec<RpcParam>,
    pub body: Option<String>,
    pub response: Option<String>,
    pub error: Option<String>,
    pub auth: RpcAuth,
    pub support: RpcRouteSupport,
    pub warnings: Vec<String>,
}

#[derive(Debug, Serialize, PartialEq, Eq)]
pub struct RpcParam {
    pub name: String,
    pub rust_type: String,
    pub variadic: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TsModel {
    pub name: String,
    pub fields: Vec<TsModelField>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TsModelField {
    pub name: String,
    pub rust_type: String,
    pub ts_type: String,
    pub optional: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TsEnum {
    pub name: String,
    pub variants: Vec<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct TsTypes {
    pub models: BTreeMap<String, TsModel>,
    pub enums: BTreeMap<String, TsEnum>,
}

#[derive(Debug, Serialize, PartialEq, Eq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum RpcAuth {
    None,
    Optional,
    Required,
    Authorized {
        policy: Option<String>,
        roles: Vec<String>,
        permissions: Vec<String>,
        scopes: Vec<String>,
        resource: Option<String>,
        mode: AuthMode,
    },
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum AuthMode {
    All,
    Any,
}

#[derive(Debug, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RpcRouteSupport {
    Json,
    Raw,
    Unsupported,
}

#[derive(Debug)]
struct RocketRouteAttr {
    method: String,
    path: String,
    data_param: Option<String>,
}

struct RocketRouteArgs {
    path: LitStr,
    data_param: Option<String>,
}

impl Parse for RocketRouteArgs {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let path = input.parse::<LitStr>()?;
        let mut data_param = None;

        while input.peek(Token![,]) {
            input.parse::<Token![,]>()?;
            if input.is_empty() {
                break;
            }

            let key = input.parse::<syn::Ident>()?;
            input.parse::<Token![=]>()?;
            let value = input.parse::<LitStr>()?;
            if key == "data" {
                data_param = Some(strip_angle_binding(&value.value()).to_owned());
            }
        }

        Ok(Self { path, data_param })
    }
}

pub fn discover_manifest(project_dir: &Path) -> Result<RpcManifest> {
    let src_dir = project_dir.join("src");
    let mut routes = Vec::new();
    visit_dir(&src_dir, &[], &mut routes)?;
    let mount_prefixes = discover_mount_prefixes(&src_dir)?;
    apply_mount_prefixes(&mount_prefixes, &mut routes);
    resolve_authorization_policies(project_dir, &mut routes)?;
    routes.sort_by(|a, b| {
        a.module_path
            .cmp(&b.module_path)
            .then_with(|| a.name.cmp(&b.name))
            .then_with(|| a.method.cmp(&b.method))
    });

    Ok(RpcManifest {
        version: MANIFEST_VERSION,
        routes,
    })
}

pub fn generate_typescript_client_with_types(manifest: &RpcManifest, types: &TsTypes) -> String {
    let json_routes = manifest
        .routes
        .iter()
        .filter(|route| route.support == RpcRouteSupport::Json)
        .collect::<Vec<_>>();
    let declarations = typescript_type_declarations(&json_routes, types);
    let methods = json_routes
        .iter()
        .map(|route| render_typescript_method(route))
        .collect::<Vec<_>>()
        .join("\n\n");

    let declarations = if declarations.is_empty() {
        String::new()
    } else {
        format!("{}\n\n", declarations.join("\n\n"))
    };

    format!(
        "/* Generated by comet rpc generate. Do not edit by hand. */\n\n\
         export type TokenProvider = () => string | null | undefined | Promise<string | null | undefined>;\n\n\
         {declarations}\
         export class CometRpcError extends Error {{\n\
         \x20 readonly status: number;\n\
         \x20 readonly body: unknown;\n\n\
         \x20 constructor(status: number, body: unknown) {{\n\
         \x20   super(`Comet RPC request failed with status ${{status}}`);\n\
         \x20   this.name = \"CometRpcError\";\n\
         \x20   this.status = status;\n\
         \x20   this.body = body;\n\
         \x20 }}\n\
         }}\n\n\
         export class CometClient {{\n\
         \x20 constructor(\n\
         \x20   private readonly baseUrl: string,\n\
         \x20   private readonly tokenProvider?: TokenProvider,\n\
         \x20 ) {{}}\n\n\
         {methods}\n\n\
         \x20 private async request<T>(method: string, path: string, body: unknown, auth: boolean): Promise<T> {{\n\
         \x20   const headers: Record<string, string> = {{ accept: \"application/json\" }};\n\
         \x20   let requestBody: string | undefined;\n\
         \x20   if (body !== undefined) {{\n\
         \x20     headers[\"content-type\"] = \"application/json\";\n\
         \x20     requestBody = JSON.stringify(body);\n\
         \x20   }}\n\
         \x20   if (auth && this.tokenProvider) {{\n\
         \x20     const token = await this.tokenProvider();\n\
         \x20     if (token) headers.authorization = `Bearer ${{token}}`;\n\
         \x20   }}\n\n\
         \x20   const response = await fetch(`${{this.baseUrl.replace(/\\/$/, \"\")}}${{path}}`, {{\n\
         \x20     method,\n\
         \x20     headers,\n\
         \x20     body: requestBody,\n\
         \x20   }});\n\
         \x20   const text = await response.text();\n\
         \x20   const payload = text ? JSON.parse(text) : undefined;\n\
         \x20   if (!response.ok) throw new CometRpcError(response.status, payload);\n\
         \x20   return payload as T;\n\
         \x20 }}\n\
         }}\n\n\
         function encodePathValue(value: string | number | boolean | Array<string | number | boolean>): string {{\n\
         \x20 if (Array.isArray(value)) return value.map((item) => encodeURIComponent(String(item))).join(\"/\");\n\
         \x20 return encodeURIComponent(String(value));\n\
         }}\n"
    )
}

pub fn generate_dart_client_with_types(manifest: &RpcManifest, types: &TsTypes) -> String {
    let json_routes = manifest
        .routes
        .iter()
        .filter(|route| route.support == RpcRouteSupport::Json)
        .collect::<Vec<_>>();
    let declarations = dart_type_declarations(&json_routes, types);
    let methods = json_routes
        .iter()
        .map(|route| render_dart_method(route))
        .collect::<Vec<_>>()
        .join("\n\n");

    let declarations = if declarations.is_empty() {
        String::new()
    } else {
        format!("{}\n\n", declarations.join("\n\n"))
    };

    format!(
        "// Generated by comet rpc generate. Do not edit by hand.\n\n\
         import 'dart:async';\n\
         import 'dart:convert';\n\n\
         import 'package:http/http.dart' as http;\n\n\
         typedef TokenProvider = FutureOr<String?> Function();\n\n\
         {declarations}\
         class CometRpcException implements Exception {{\n\
         \x20 final int status;\n\
         \x20 final Object? body;\n\n\
         \x20 CometRpcException(this.status, this.body);\n\n\
         \x20 @override\n\
         \x20 String toString() => 'CometRpcException(status: $status)';\n\
         }}\n\n\
         class CometClient {{\n\
         \x20 final String baseUrl;\n\
         \x20 final TokenProvider? tokenProvider;\n\
         \x20 final http.Client _http;\n\n\
         \x20 CometClient(this.baseUrl, {{this.tokenProvider, http.Client? httpClient}})\n\
         \x20     : _http = httpClient ?? http.Client();\n\n\
         {methods}\n\n\
         \x20 Future<T> _request<T>(String method, String path, Object? body, bool auth, T Function(Object?) decode) async {{\n\
         \x20   final headers = <String, String>{{'accept': 'application/json'}};\n\
         \x20   String? requestBody;\n\
         \x20   if (body != null) {{\n\
         \x20     headers['content-type'] = 'application/json';\n\
         \x20     requestBody = jsonEncode(_toJson(body));\n\
         \x20   }}\n\
         \x20   if (auth && tokenProvider != null) {{\n\
         \x20     final token = await tokenProvider!();\n\
         \x20     if (token != null && token.isNotEmpty) headers['authorization'] = 'Bearer $token';\n\
         \x20   }}\n\n\
         \x20   final uri = Uri.parse('${{baseUrl.replaceFirst(RegExp(r'/\\$'), '')}}$path');\n\
         \x20   final response = await _http.send(http.Request(method, uri)\n\
         \x20     ..headers.addAll(headers)\n\
         \x20     ..body = requestBody ?? '');\n\
         \x20   final text = await response.stream.bytesToString();\n\
         \x20   final payload = text.isEmpty ? null : jsonDecode(text);\n\
         \x20   if (response.statusCode < 200 || response.statusCode >= 300) {{\n\
         \x20     throw CometRpcException(response.statusCode, payload);\n\
         \x20   }}\n\
         \x20   return decode(payload);\n\
         \x20 }}\n\
         }}\n\n\
         Object? _toJson(Object? value) {{\n\
         \x20 if (value == null) return null;\n\
         \x20 if (value is List) return value.map(_toJson).toList();\n\
         \x20 if (value is Map) return value.map((key, value) => MapEntry(key, _toJson(value)));\n\
         \x20 try {{\n\
         \x20   return (value as dynamic).toJson();\n\
         \x20 }} catch (_) {{\n\
         \x20   return value;\n\
         \x20 }}\n\
         }}\n\n\
         String _encodePathValue(Object value) {{\n\
         \x20 if (value is List) return value.map((item) => Uri.encodeComponent('$item')).join('/');\n\
         \x20 return Uri.encodeComponent('$value');\n\
         }}\n"
    )
}

pub fn discover_typescript_types(project_dir: &Path, manifest: &RpcManifest) -> Result<TsTypes> {
    let mut wanted = typescript_type_names_for_manifest(manifest);
    if wanted.is_empty() {
        return Ok(TsTypes::default());
    }

    let src_dir = project_dir.join("src");
    let mut types = TsTypes::default();
    let mut scanned = std::collections::BTreeSet::new();

    loop {
        let pending = wanted
            .difference(&scanned)
            .cloned()
            .collect::<std::collections::BTreeSet<_>>();
        if pending.is_empty() {
            break;
        }

        visit_model_dir(&src_dir, &pending, &mut types)?;
        scanned.extend(pending);

        for model in types.models.values() {
            for field in &model.fields {
                collect_custom_type_names(&field.rust_type, &mut wanted);
            }
        }
    }

    Ok(types)
}

fn visit_model_dir(
    dir: &Path,
    wanted: &std::collections::BTreeSet<String>,
    types: &mut TsTypes,
) -> Result<()> {
    let mut dir_entries = fs::read_dir(dir)
        .with_context(|| format!("reading directory {}", dir.display()))?
        .collect::<std::io::Result<Vec<_>>>()
        .with_context(|| format!("reading directory {}", dir.display()))?;
    dir_entries.sort_by_key(|entry| entry.file_name());

    for entry in dir_entries {
        let path = entry.path();
        let file_type = entry
            .file_type()
            .with_context(|| format!("reading file type of {}", path.display()))?;

        if file_type.is_dir() {
            visit_model_dir(&path, wanted, types)?;
        } else if path.extension().and_then(|ext| ext.to_str()) == Some("rs") {
            visit_model_file(&path, wanted, types)?;
        }
    }

    Ok(())
}

fn visit_model_file(
    path: &Path,
    wanted: &std::collections::BTreeSet<String>,
    types: &mut TsTypes,
) -> Result<()> {
    let source = fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let file = syn::parse_file(&source).with_context(|| format!("parsing {}", path.display()))?;

    for item in &file.items {
        match item {
            Item::Struct(item_struct) => {
                let name = item_struct.ident.to_string();
                if wanted.contains(&name)
                    && let Some(model) = ts_model_from_struct(item_struct)
                {
                    types.models.insert(name, model);
                }
            }
            Item::Enum(item_enum) => {
                let name = item_enum.ident.to_string();
                if wanted.contains(&name)
                    && let Some(ts_enum) = ts_enum_from_enum(item_enum)
                {
                    types.enums.insert(name, ts_enum);
                }
            }
            _ => {}
        }
    }

    Ok(())
}

fn ts_model_from_struct(item_struct: &syn::ItemStruct) -> Option<TsModel> {
    let Fields::Named(fields) = &item_struct.fields else {
        return None;
    };

    let mut model_fields = Vec::new();
    for field in &fields.named {
        let Some(model_field) = ts_model_field(field) else {
            continue;
        };
        model_fields.push(model_field);
    }

    Some(TsModel {
        name: item_struct.ident.to_string(),
        fields: model_fields,
    })
}

fn ts_model_field(field: &Field) -> Option<TsModelField> {
    if !matches!(field.vis, Visibility::Public(_)) {
        return None;
    }

    let ident = field.ident.as_ref()?.to_string();
    if serde_skip(&field.attrs) {
        return None;
    }
    let name = serde_rename(&field.attrs).unwrap_or(ident);
    let rust_type = type_to_string(&field.ty);
    let optional = generic_inner_for_last_segment(&rust_type, "Option").is_some();

    Some(TsModelField {
        name,
        rust_type: rust_type.clone(),
        ts_type: rust_type_to_typescript(&rust_type),
        optional,
    })
}

fn ts_enum_from_enum(item_enum: &syn::ItemEnum) -> Option<TsEnum> {
    let rename_all = serde_rename_all(&item_enum.attrs);
    let mut variants = Vec::new();

    for variant in &item_enum.variants {
        if !matches!(variant.fields, Fields::Unit) {
            return None;
        }
        let fallback = rename_variant(&variant.ident.to_string(), rename_all.as_deref());
        variants.push(serde_rename(&variant.attrs).unwrap_or(fallback));
    }

    Some(TsEnum {
        name: item_enum.ident.to_string(),
        variants,
    })
}

fn serde_skip(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|attr| {
        attr.path().is_ident("serde")
            && attr
                .parse_args_with(Punctuated::<syn::Meta, Token![,]>::parse_terminated)
                .ok()
                .is_some_and(|metas| {
                    metas.iter().any(|meta| match meta {
                        syn::Meta::Path(path) => path.is_ident("skip"),
                        syn::Meta::NameValue(name_value) => name_value.path.is_ident("skip"),
                        syn::Meta::List(list) => list.path.is_ident("skip"),
                    })
                })
    })
}

fn serde_rename(attrs: &[Attribute]) -> Option<String> {
    for attr in attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        let metas = attr
            .parse_args_with(Punctuated::<syn::Meta, Token![,]>::parse_terminated)
            .ok()?;
        for meta in metas {
            let syn::Meta::NameValue(name_value) = meta else {
                continue;
            };
            if !name_value.path.is_ident("rename") {
                continue;
            }
            let syn::Expr::Lit(expr_lit) = name_value.value else {
                continue;
            };
            let Lit::Str(value) = expr_lit.lit else {
                continue;
            };
            return Some(value.value());
        }
    }

    None
}

fn serde_rename_all(attrs: &[Attribute]) -> Option<String> {
    for attr in attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        let metas = attr
            .parse_args_with(Punctuated::<syn::Meta, Token![,]>::parse_terminated)
            .ok()?;
        for meta in metas {
            let syn::Meta::NameValue(name_value) = meta else {
                continue;
            };
            if !name_value.path.is_ident("rename_all") {
                continue;
            }
            let syn::Expr::Lit(expr_lit) = name_value.value else {
                continue;
            };
            let Lit::Str(value) = expr_lit.lit else {
                continue;
            };
            return Some(value.value());
        }
    }

    None
}

fn rename_variant(name: &str, rename_all: Option<&str>) -> String {
    match rename_all {
        Some("snake_case") => to_snake_case(name),
        Some("kebab-case") => to_snake_case(name).replace('_', "-"),
        Some("SCREAMING_SNAKE_CASE") => to_snake_case(name).to_ascii_uppercase(),
        Some("camelCase") => to_lower_camel_case(name),
        Some("PascalCase") | None => name.to_owned(),
        Some(_) => name.to_owned(),
    }
}

fn to_snake_case(value: &str) -> String {
    let mut output = String::new();
    let mut previous_was_lower_or_digit = false;
    for ch in value.chars() {
        if ch.is_ascii_uppercase() {
            if previous_was_lower_or_digit && !output.is_empty() {
                output.push('_');
            }
            output.push(ch.to_ascii_lowercase());
            previous_was_lower_or_digit = false;
        } else if ch == '-' || ch.is_whitespace() {
            if !output.ends_with('_') && !output.is_empty() {
                output.push('_');
            }
            previous_was_lower_or_digit = false;
        } else {
            output.push(ch);
            previous_was_lower_or_digit = ch.is_ascii_lowercase() || ch.is_ascii_digit();
        }
    }
    output
}

fn discover_mount_prefixes(src_dir: &Path) -> Result<BTreeMap<String, Vec<String>>> {
    let mut prefixes = BTreeMap::new();
    visit_mount_dir(src_dir, &mut prefixes)?;
    Ok(prefixes)
}

fn visit_mount_dir(dir: &Path, prefixes: &mut BTreeMap<String, Vec<String>>) -> Result<()> {
    let mut dir_entries = fs::read_dir(dir)
        .with_context(|| format!("reading directory {}", dir.display()))?
        .collect::<std::io::Result<Vec<_>>>()
        .with_context(|| format!("reading directory {}", dir.display()))?;
    dir_entries.sort_by_key(|entry| entry.file_name());

    for entry in dir_entries {
        let path = entry.path();
        let file_type = entry
            .file_type()
            .with_context(|| format!("reading file type of {}", path.display()))?;

        if file_type.is_dir() {
            visit_mount_dir(&path, prefixes)?;
        } else if path.extension().and_then(|ext| ext.to_str()) == Some("rs") {
            visit_mount_file(&path, prefixes)?;
        }
    }

    Ok(())
}

fn visit_mount_file(path: &Path, prefixes: &mut BTreeMap<String, Vec<String>>) -> Result<()> {
    let source = fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let file = syn::parse_file(&source).with_context(|| format!("parsing {}", path.display()))?;
    let mut visitor = MountVisitor { prefixes };
    visitor.visit_file(&file);
    Ok(())
}

struct MountVisitor<'a> {
    prefixes: &'a mut BTreeMap<String, Vec<String>>,
}

impl<'ast> Visit<'ast> for MountVisitor<'_> {
    fn visit_expr_method_call(&mut self, node: &'ast ExprMethodCall) {
        if node.method == "mount"
            && let Some(prefix) = mount_prefix(node)
        {
            for route_name in mounted_route_names(node) {
                self.prefixes
                    .entry(route_name)
                    .or_default()
                    .push(prefix.clone());
            }
        }

        visit::visit_expr_method_call(self, node);
    }
}

fn mount_prefix(node: &ExprMethodCall) -> Option<String> {
    let Expr::Lit(expr_lit) = node.args.first()? else {
        return None;
    };
    let Lit::Str(prefix) = &expr_lit.lit else {
        return None;
    };
    Some(prefix.value())
}

fn mounted_route_names(node: &ExprMethodCall) -> Vec<String> {
    let Some(Expr::Macro(expr_macro)) = node.args.iter().nth(1) else {
        return Vec::new();
    };
    if !expr_macro
        .mac
        .path
        .segments
        .last()
        .is_some_and(|segment| segment.ident == "routes")
    {
        return Vec::new();
    }

    expr_macro
        .mac
        .parse_body_with(Punctuated::<syn::Path, Token![,]>::parse_terminated)
        .ok()
        .map(|paths| {
            paths
                .iter()
                .filter_map(|path| path.segments.last())
                .map(|segment| segment.ident.to_string())
                .collect()
        })
        .unwrap_or_default()
}

fn apply_mount_prefixes(mount_prefixes: &BTreeMap<String, Vec<String>>, routes: &mut [RpcRoute]) {
    for route in routes {
        let Some(prefixes) = mount_prefixes.get(&route.name) else {
            continue;
        };

        let unique = prefixes.iter().collect::<std::collections::BTreeSet<_>>();
        if unique.len() > 1 {
            route.warnings.push(format!(
                "route `{}` is mounted at multiple prefixes; leaving local path unchanged",
                route.name
            ));
            continue;
        }

        if let Some(prefix) = prefixes.first() {
            route.path = join_mount_path(prefix, &route.path);
        }
    }
}

fn join_mount_path(prefix: &str, route_path: &str) -> String {
    let prefix = prefix.trim_end_matches('/');
    let route_path = route_path.trim_start_matches('/');

    match (prefix.is_empty(), route_path.is_empty()) {
        (true, true) => "/".to_owned(),
        (true, false) => format!("/{route_path}"),
        (false, true) => prefix.to_owned(),
        (false, false) => format!("{prefix}/{route_path}"),
    }
}

fn render_typescript_method(route: &RpcRoute) -> String {
    let method_name = to_lower_camel_case(&route.name);
    let return_type = route
        .response
        .as_deref()
        .map(rust_type_to_typescript)
        .unwrap_or_else(|| "unknown".to_owned());
    let mut params = route
        .path_params
        .iter()
        .map(|param| {
            let ts_type = if param.variadic {
                "string | number | Array<string | number>".to_owned()
            } else {
                rust_type_to_typescript(&param.rust_type)
            };
            format!("{}: {}", sanitize_ts_identifier(&param.name), ts_type)
        })
        .collect::<Vec<_>>();

    let body_arg = route.data_param.as_deref().unwrap_or("body");
    if let Some(body) = &route.body {
        params.push(format!(
            "{}: {}",
            sanitize_ts_identifier(body_arg),
            rust_type_to_typescript(body)
        ));
    }

    let body_expr = if route.body.is_some() {
        sanitize_ts_identifier(body_arg)
    } else {
        "undefined".to_owned()
    };
    let auth = !matches!(route.auth, RpcAuth::None);
    let path = typescript_path_template(route);

    format!(
        "  async {method_name}({params}): Promise<{return_type}> {{\n\
         \x20   return this.request<{return_type}>(\"{method}\", {path}, {body_expr}, {auth});\n\
         \x20 }}",
        params = params.join(", "),
        method = route.method,
    )
}

fn typescript_path_template(route: &RpcRoute) -> String {
    let mut path = route.path.clone();
    for param in &route.path_params {
        let ident = sanitize_ts_identifier(&param.name);
        let placeholder = if param.variadic {
            format!("<{}..>", param.name)
        } else {
            format!("<{}>", param.name)
        };
        path = path.replace(&placeholder, &format!("${{encodePathValue({ident})}}"));
    }

    format!("`{}`", path.replace('`', "\\`"))
}

fn typescript_type_declarations(routes: &[&RpcRoute], types: &TsTypes) -> Vec<String> {
    let mut names = typescript_type_names(routes);
    names.extend(types.models.keys().cloned());
    names.extend(types.enums.keys().cloned());
    names
        .into_iter()
        .map(|name| {
            if let Some(model) = types.models.get(&name) {
                render_typescript_interface(model)
            } else if let Some(ts_enum) = types.enums.get(&name) {
                render_typescript_enum(ts_enum)
            } else {
                format!("export type {name} = unknown;")
            }
        })
        .collect()
}

fn render_typescript_enum(ts_enum: &TsEnum) -> String {
    let variants = ts_enum
        .variants
        .iter()
        .map(|variant| format!("{variant:?}"))
        .collect::<Vec<_>>()
        .join(" | ");
    format!("export type {} = {};", ts_enum.name, variants)
}

fn render_typescript_interface(model: &TsModel) -> String {
    let fields = model
        .fields
        .iter()
        .map(|field| {
            let optional = if field.optional { "?" } else { "" };
            format!(
                "  {}{}: {};",
                typescript_property_name(&field.name),
                optional,
                field.ts_type
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    if fields.is_empty() {
        format!("export interface {} {{}}", model.name)
    } else {
        format!("export interface {} {{\n{}\n}}", model.name, fields)
    }
}

fn dart_type_declarations(routes: &[&RpcRoute], types: &TsTypes) -> Vec<String> {
    let mut names = typescript_type_names(routes);
    names.extend(types.models.keys().cloned());
    names.extend(types.enums.keys().cloned());
    names
        .into_iter()
        .map(|name| {
            if let Some(model) = types.models.get(&name) {
                render_dart_class(model)
            } else if let Some(ts_enum) = types.enums.get(&name) {
                render_dart_enum(ts_enum)
            } else {
                format!("typedef {name} = Object?;")
            }
        })
        .collect()
}

fn render_dart_class(model: &TsModel) -> String {
    let fields = model
        .fields
        .iter()
        .map(|field| {
            format!(
                "  final {} {};",
                dart_type_from_rust(&field.rust_type),
                sanitize_dart_identifier(&field.name)
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let ctor_params = model
        .fields
        .iter()
        .map(|field| format!("required this.{}", sanitize_dart_identifier(&field.name)))
        .collect::<Vec<_>>()
        .join(", ");
    let from_json_fields = model
        .fields
        .iter()
        .map(|field| {
            format!(
                "      {}: {},",
                sanitize_dart_identifier(&field.name),
                dart_json_decode_expr(&field.rust_type, &format!("json[{:?}]", field.name))
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let to_json_fields = model
        .fields
        .iter()
        .map(|field| {
            let ident = sanitize_dart_identifier(&field.name);
            format!("      {:?}: _toJson({ident}),", field.name)
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "class {name} {{\n\
         {fields}\n\n\
         \x20 const {name}({{{ctor_params}}});\n\n\
         \x20 factory {name}.fromJson(Object? value) {{\n\
         \x20   final json = value as Map<String, dynamic>;\n\
         \x20   return {name}(\n\
         {from_json_fields}\n\
         \x20   );\n\
         \x20 }}\n\n\
         \x20 Map<String, dynamic> toJson() => {{\n\
         {to_json_fields}\n\
         \x20 }};\n\
         }}",
        name = model.name
    )
}

fn render_dart_enum(ts_enum: &TsEnum) -> String {
    let constants = ts_enum
        .variants
        .iter()
        .map(|variant| {
            format!(
                "  {}({:?})",
                sanitize_dart_identifier(&to_lower_camel_case(variant)),
                variant
            )
        })
        .collect::<Vec<_>>()
        .join(",\n");

    format!(
        "enum {name} {{\n\
         {constants};\n\n\
         \x20 final String value;\n\
         \x20 const {name}(this.value);\n\n\
         \x20 static {name} fromJson(Object? value) {{\n\
         \x20   return {name}.values.firstWhere((item) => item.value == value);\n\
         \x20 }}\n\n\
         \x20 String toJson() => value;\n\
         }}",
        name = ts_enum.name
    )
}

fn render_dart_method(route: &RpcRoute) -> String {
    let method_name = to_lower_camel_case(&route.name);
    let return_type = route
        .response
        .as_deref()
        .map(dart_type_from_rust)
        .unwrap_or_else(|| "Object?".to_owned());
    let mut params = route
        .path_params
        .iter()
        .map(|param| {
            let dart_type = if param.variadic {
                "List<Object>".to_owned()
            } else {
                dart_type_from_rust(&param.rust_type)
            };
            format!("{} {}", dart_type, sanitize_dart_identifier(&param.name))
        })
        .collect::<Vec<_>>();

    let body_arg = route.data_param.as_deref().unwrap_or("body");
    if let Some(body) = &route.body {
        params.push(format!(
            "{} {}",
            dart_type_from_rust(body),
            sanitize_dart_identifier(body_arg)
        ));
    }

    let body_expr = if route.body.is_some() {
        sanitize_dart_identifier(body_arg)
    } else {
        "null".to_owned()
    };
    let auth = !matches!(route.auth, RpcAuth::None);
    let path = dart_path_template(route);
    let decode = dart_decode_closure(route.response.as_deref());

    format!(
        "  Future<{return_type}> {method_name}({params}) async {{\n\
         \x20   return _request<{return_type}>('{method}', {path}, {body_expr}, {auth}, {decode});\n\
         \x20 }}",
        params = params.join(", "),
        method = route.method,
    )
}

fn dart_path_template(route: &RpcRoute) -> String {
    let mut path = route.path.clone();
    for param in &route.path_params {
        let ident = sanitize_dart_identifier(&param.name);
        let placeholder = if param.variadic {
            format!("<{}..>", param.name)
        } else {
            format!("<{}>", param.name)
        };
        path = path.replace(&placeholder, &format!("${{_encodePathValue({ident})}}"));
    }
    format!("'{path}'")
}

fn dart_decode_closure(rust_type: Option<&str>) -> String {
    match rust_type {
        Some(rust_type) => format!("(value) => {}", dart_json_decode_expr(rust_type, "value")),
        None => "(_) => null".to_owned(),
    }
}

fn dart_json_decode_expr(rust_type: &str, value: &str) -> String {
    let rust_type = rust_type.trim();
    if let Some(inner) = generic_inner_for_last_segment(rust_type, "Option") {
        return format!(
            "{value} == null ? null : {}",
            dart_json_decode_expr(&inner, value)
        );
    }
    if let Some(inner) = generic_inner_for_last_segment(rust_type, "Vec") {
        return format!(
            "({value} as List).map((item) => {}).toList()",
            dart_json_decode_expr(&inner, "item")
        );
    }

    match rust_type {
        "String" | "& str" | "&str" | "& 'static str" => format!("{value} as String"),
        "bool" => format!("{value} as bool"),
        "i8" | "i16" | "i32" | "i64" | "isize" | "u8" | "u16" | "u32" | "u64" | "usize" => {
            format!("{value} as int")
        }
        "f32" | "f64" => format!("({value} as num).toDouble()"),
        other => {
            let name = type_last_segment(other).unwrap_or(other).replace(' ', "");
            if is_valid_ts_type_name(&name) {
                format!("{name}.fromJson({value})")
            } else {
                value.to_owned()
            }
        }
    }
}

fn dart_type_from_rust(rust_type: &str) -> String {
    let rust_type = rust_type.trim();
    if let Some(inner) = generic_inner_for_last_segment(rust_type, "Option") {
        return format!("{}?", dart_type_from_rust(&inner).trim_end_matches('?'));
    }
    if let Some(inner) = generic_inner_for_last_segment(rust_type, "Vec") {
        return format!("List<{}>", dart_type_from_rust(&inner));
    }

    match rust_type {
        "String" | "& str" | "&str" | "& 'static str" => "String".to_owned(),
        "bool" => "bool".to_owned(),
        "i8" | "i16" | "i32" | "i64" | "isize" | "u8" | "u16" | "u32" | "u64" | "usize" => {
            "int".to_owned()
        }
        "f32" | "f64" => "double".to_owned(),
        "()" => "void".to_owned(),
        other => type_last_segment(other).unwrap_or(other).replace(' ', ""),
    }
}

fn typescript_type_names_for_manifest(
    manifest: &RpcManifest,
) -> std::collections::BTreeSet<String> {
    let routes = manifest
        .routes
        .iter()
        .filter(|route| route.support == RpcRouteSupport::Json)
        .collect::<Vec<_>>();
    typescript_type_names(&routes)
}

fn typescript_type_names(routes: &[&RpcRoute]) -> std::collections::BTreeSet<String> {
    let mut names = std::collections::BTreeSet::new();
    for route in routes {
        if let Some(body) = &route.body {
            collect_custom_type_names(body, &mut names);
        }
        if let Some(response) = &route.response {
            collect_custom_type_names(response, &mut names);
        }
    }
    names
}

fn collect_custom_type_names(rust_type: &str, names: &mut std::collections::BTreeSet<String>) {
    let rust_type = rust_type.trim();
    for wrapper in ["Json", "Vec", "Option"] {
        if let Some(inner) = generic_inner_for_last_segment(rust_type, wrapper) {
            for part in split_top_level_commas(&inner) {
                collect_custom_type_names(&part, names);
            }
            return;
        }
    }

    if is_primitive_rust_type(rust_type) {
        return;
    }

    let name = type_last_segment(rust_type).unwrap_or(rust_type).trim();
    if is_valid_ts_type_name(name) {
        names.insert(name.to_owned());
    }
}

fn typescript_property_name(name: &str) -> String {
    if is_valid_ts_identifier(name) {
        name.to_owned()
    } else {
        format!("{name:?}")
    }
}

fn rust_type_to_typescript(rust_type: &str) -> String {
    let rust_type = rust_type.trim();
    if let Some(inner) = generic_inner_for_last_segment(rust_type, "Vec") {
        return format!("Array<{}>", rust_type_to_typescript(&inner));
    }
    if let Some(inner) = generic_inner_for_last_segment(rust_type, "Option") {
        return format!("{} | null", rust_type_to_typescript(&inner));
    }

    match rust_type {
        "String" | "& str" | "&str" | "& 'static str" => "string".to_owned(),
        "bool" => "boolean".to_owned(),
        "i8" | "i16" | "i32" | "i64" | "isize" | "u8" | "u16" | "u32" | "u64" | "usize" | "f32"
        | "f64" => "number".to_owned(),
        "()" => "void".to_owned(),
        other => type_last_segment(other).unwrap_or(other).replace(' ', ""),
    }
}

fn is_primitive_rust_type(rust_type: &str) -> bool {
    matches!(
        rust_type,
        "String"
            | "& str"
            | "&str"
            | "& 'static str"
            | "bool"
            | "i8"
            | "i16"
            | "i32"
            | "i64"
            | "isize"
            | "u8"
            | "u16"
            | "u32"
            | "u64"
            | "usize"
            | "f32"
            | "f64"
            | "()"
    )
}

fn to_lower_camel_case(value: &str) -> String {
    let mut output = String::new();
    for (index, part) in value
        .split(|ch: char| ch == '_' || ch == '-' || ch.is_whitespace())
        .filter(|part| !part.is_empty())
        .enumerate()
    {
        if index == 0 {
            output.push_str(&part.to_ascii_lowercase());
        } else {
            let mut chars = part.chars();
            if let Some(first) = chars.next() {
                output.push(first.to_ascii_uppercase());
                output.push_str(&chars.as_str().to_ascii_lowercase());
            }
        }
    }
    output
}

fn sanitize_ts_identifier(value: &str) -> String {
    let mut ident = String::new();
    for (index, ch) in value.chars().enumerate() {
        if ch == '_' || ch.is_ascii_alphanumeric() {
            if index == 0 && ch.is_ascii_digit() {
                ident.push('_');
            }
            ident.push(ch);
        } else {
            ident.push('_');
        }
    }

    if ident.is_empty() {
        "value".to_owned()
    } else {
        ident
    }
}

fn sanitize_dart_identifier(value: &str) -> String {
    let mut ident = String::new();
    for (index, ch) in value.chars().enumerate() {
        if ch == '_' || ch.is_ascii_alphanumeric() {
            if index == 0 && ch.is_ascii_digit() {
                ident.push('_');
            }
            ident.push(ch);
        } else {
            ident.push('_');
        }
    }

    match ident.as_str() {
        "" => "value".to_owned(),
        "class" | "enum" | "final" | "import" | "return" | "void" | "true" | "false" | "null" => {
            format!("{ident}_")
        }
        _ => ident,
    }
}

fn is_valid_ts_type_name(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first == '_' || first.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

fn is_valid_ts_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first == '_' || first == '$' || first.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch == '$' || ch.is_ascii_alphanumeric())
}

fn resolve_authorization_policies(project_dir: &Path, routes: &mut [RpcRoute]) -> Result<()> {
    let pending = routes
        .iter()
        .filter_map(|route| {
            let RpcAuth::Authorized {
                policy: Some(policy),
                roles,
                permissions,
                scopes,
                ..
            } = &route.auth
            else {
                return None;
            };

            if !roles.is_empty() || !permissions.is_empty() || !scopes.is_empty() {
                return None;
            }

            Some(PolicyRef {
                display: policy.clone(),
                path: String::new(),
                module_path: route.module_path.clone(),
            })
        })
        .collect::<Vec<_>>();

    if pending.is_empty() {
        return Ok(());
    }

    if !project_dir.join("Cargo.toml").exists() {
        for route in routes {
            if let RpcAuth::Authorized {
                policy: Some(policy),
                roles,
                permissions,
                scopes,
                ..
            } = &route.auth
                && roles.is_empty()
                && permissions.is_empty()
                && scopes.is_empty()
            {
                route.warnings.push(format!(
                    "authorization policy `{policy}` was not resolved because the project has no Cargo.toml"
                ));
            }
        }
        return Ok(());
    }

    let project = RustProject::read(project_dir)?;
    let policy_refs = pending
        .into_iter()
        .map(|policy_ref| PolicyRef {
            path: policy_path(
                &policy_ref.display,
                &policy_ref.module_path,
                &project.crate_name,
            ),
            ..policy_ref
        })
        .collect::<Vec<_>>();
    let requirements = dump_authorization_requirements(&project, &policy_refs)?;

    for route in routes {
        let RpcAuth::Authorized {
            policy: Some(policy),
            roles,
            permissions,
            scopes,
            resource,
            mode,
        } = &mut route.auth
        else {
            continue;
        };

        if !roles.is_empty() || !permissions.is_empty() || !scopes.is_empty() {
            continue;
        }

        let path = policy_path(policy, &route.module_path, &project.crate_name);
        if let Some(requirement) = requirements.iter().find(|entry| entry.path == path) {
            *roles = requirement.roles.clone();
            *permissions = requirement.permissions.clone();
            *scopes = requirement.scopes.clone();
            *resource = requirement.resource.clone();
            *mode = requirement.mode.clone();
        } else {
            route.warnings.push(format!(
                "authorization policy `{policy}` could not be resolved"
            ));
        }
    }

    Ok(())
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
struct PolicyRef {
    display: String,
    path: String,
    module_path: Vec<String>,
}

#[derive(Debug)]
struct RustProject {
    dir: PathBuf,
    package_name: String,
    crate_name: String,
    comet_auth_dependency: Value,
}

#[derive(Debug, Deserialize)]
struct AuthorizationRequirementDump {
    path: String,
    mode: AuthMode,
    roles: Vec<String>,
    permissions: Vec<String>,
    scopes: Vec<String>,
    resource: Option<String>,
}

impl<'de> Deserialize<'de> for AuthMode {
    fn deserialize<D>(deserializer: D) -> std::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "all" => Ok(Self::All),
            "any" => Ok(Self::Any),
            other => Err(serde::de::Error::custom(format!(
                "unsupported authorization mode `{other}`"
            ))),
        }
    }
}

impl RustProject {
    fn read(project_dir: &Path) -> Result<Self> {
        let dir = project_dir
            .canonicalize()
            .with_context(|| format!("resolving {}", project_dir.display()))?;
        let cargo_toml_path = dir.join("Cargo.toml");
        let cargo_toml_text = fs::read_to_string(&cargo_toml_path)
            .with_context(|| format!("reading {}", cargo_toml_path.display()))?;
        let root: Value = toml::from_str(&cargo_toml_text)
            .with_context(|| format!("parsing {}", cargo_toml_path.display()))?;

        let package_name = root
            .get("package")
            .and_then(|package| package.get("name"))
            .and_then(Value::as_str)
            .with_context(|| format!("{} has no [package].name", cargo_toml_path.display()))?
            .to_owned();
        let crate_name = package_name.replace('-', "_");

        let comet_auth_dependency = root
            .get("dependencies")
            .and_then(|deps| deps.get("comet-auth"))
            .with_context(|| {
                format!(
                    "{} has no [dependencies].comet-auth entry",
                    cargo_toml_path.display()
                )
            })?
            .clone();
        let mut comet_auth_dependency = dependency_as_table(&comet_auth_dependency)?;
        resolve_relative_path(&mut comet_auth_dependency, &dir)?;

        Ok(Self {
            dir,
            package_name,
            crate_name,
            comet_auth_dependency,
        })
    }
}

fn dump_authorization_requirements(
    project: &RustProject,
    policy_refs: &[PolicyRef],
) -> Result<Vec<AuthorizationRequirementDump>> {
    if policy_refs.is_empty() {
        return Ok(Vec::new());
    }

    let mut policy_refs = policy_refs.to_vec();
    policy_refs.sort();
    policy_refs.dedup_by(|a, b| a.path == b.path);

    let temp_dir = tempfile::tempdir().context("creating rpc-dump temp directory")?;
    fs::write(
        temp_dir.path().join("Cargo.toml"),
        build_rpc_dump_manifest(project)?,
    )
    .context("writing rpc-dump Cargo.toml")?;
    fs::create_dir_all(temp_dir.path().join("src")).context("creating rpc-dump src/")?;
    fs::write(
        temp_dir.path().join("src/main.rs"),
        render_auth_dump_main_rs(&policy_refs),
    )
    .context("writing rpc-dump main.rs")?;

    let output = Command::new("cargo")
        .arg("run")
        .arg("--quiet")
        .current_dir(temp_dir.path())
        .output()
        .context("running cargo for the rpc-dump crate")?;

    if !output.status.success() {
        bail!(
            "RPC authorization policy dump failed:\n{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    let json =
        String::from_utf8(output.stdout).context("RPC authorization dump produced non-UTF8")?;
    serde_json::from_str(&json).context("parsing RPC authorization dump JSON")
}

fn build_rpc_dump_manifest(project: &RustProject) -> Result<String> {
    let mut target_dependency = toml::Table::new();
    target_dependency.insert(
        "path".to_owned(),
        Value::String(project.dir.display().to_string()),
    );

    let mut dependencies = toml::Table::new();
    dependencies.insert(
        project.package_name.clone(),
        Value::Table(target_dependency),
    );
    dependencies.insert(
        "comet-auth".to_owned(),
        project.comet_auth_dependency.clone(),
    );
    dependencies.insert("serde_json".to_owned(), Value::String("1".to_owned()));

    let mut package = toml::Table::new();
    package.insert(
        "name".to_owned(),
        Value::String("comet-rpc-dump".to_owned()),
    );
    package.insert("version".to_owned(), Value::String("0.0.0".to_owned()));
    package.insert("edition".to_owned(), Value::String("2021".to_owned()));
    package.insert("publish".to_owned(), Value::Boolean(false));

    let mut root = toml::Table::new();
    root.insert("package".to_owned(), Value::Table(package));
    root.insert("dependencies".to_owned(), Value::Table(dependencies));

    toml::to_string_pretty(&Value::Table(root)).context("rendering rpc-dump Cargo.toml")
}

fn render_auth_dump_main_rs(policy_refs: &[PolicyRef]) -> String {
    let entries = policy_refs
        .iter()
        .map(|policy_ref| {
            let path = &policy_ref.path;
            format!(
                "    {{\n\
                 \x20       let requirement = <{path} as ::comet_auth::RequiredAuthorization>::REQUIREMENT;\n\
                 \x20       values.push(::serde_json::json!({{\n\
                 \x20           \"path\": \"{path}\",\n\
                 \x20           \"mode\": match requirement.mode {{\n\
                 \x20               ::comet_auth::AuthorizationMode::All => \"all\",\n\
                 \x20               ::comet_auth::AuthorizationMode::Any => \"any\",\n\
                 \x20           }},\n\
                 \x20           \"roles\": requirement.roles,\n\
                 \x20           \"permissions\": requirement.permissions,\n\
                 \x20           \"scopes\": requirement.scopes,\n\
                 \x20           \"resource\": requirement.resource,\n\
                 \x20       }}));\n\
                 \x20   }}"
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "fn main() {{\n\
         \x20   let mut values = Vec::new();\n\
         {entries}\n\
         \x20   print!(\"{{}}\", ::serde_json::to_string(&values).unwrap());\n\
         }}\n"
    )
}

fn dependency_as_table(dependency: &Value) -> Result<Value> {
    match dependency {
        Value::String(version) => {
            let mut table = toml::Table::new();
            table.insert("version".to_owned(), Value::String(version.clone()));
            Ok(Value::Table(table))
        }
        Value::Table(table) => Ok(Value::Table(table.clone())),
        other => bail!("unsupported dependency format in Cargo.toml: {other:?}"),
    }
}

fn resolve_relative_path(dependency: &mut Value, base_dir: &Path) -> Result<()> {
    let Value::Table(table) = dependency else {
        return Ok(());
    };
    let Some(Value::String(path_str)) = table.get("path").cloned() else {
        return Ok(());
    };

    let path = Path::new(&path_str);
    let absolute = if path.is_absolute() {
        path.to_path_buf()
    } else {
        base_dir.join(path)
    };
    let absolute = absolute
        .canonicalize()
        .with_context(|| format!("resolving path dependency {}", absolute.display()))?;

    table.insert(
        "path".to_owned(),
        Value::String(absolute.display().to_string()),
    );
    Ok(())
}

fn policy_path(policy: &str, module_path: &[String], crate_name: &str) -> String {
    if let Some(rest) = policy.strip_prefix("crate ::") {
        return format!("{crate_name}::{rest}").replace(" :: ", "::");
    }
    if let Some(rest) = policy.strip_prefix("crate::") {
        return format!("{crate_name}::{rest}");
    }
    if policy.starts_with("::") {
        return policy.trim_start_matches("::").replace(" :: ", "::");
    }
    if policy.contains("::") || policy.contains(" :: ") {
        return policy.replace(" :: ", "::");
    }

    let mut segments = vec![crate_name.to_owned()];
    segments.extend(module_path.iter().cloned());
    segments.push(policy.to_owned());
    segments.join("::")
}

fn visit_dir(dir: &Path, module_path: &[String], routes: &mut Vec<RpcRoute>) -> Result<()> {
    let mut dir_entries = fs::read_dir(dir)
        .with_context(|| format!("reading directory {}", dir.display()))?
        .collect::<std::io::Result<Vec<_>>>()
        .with_context(|| format!("reading directory {}", dir.display()))?;
    dir_entries.sort_by_key(|entry| entry.file_name());

    for entry in dir_entries {
        let path = entry.path();
        let file_type = entry
            .file_type()
            .with_context(|| format!("reading file type of {}", path.display()))?;

        if file_type.is_dir() {
            let mut nested_path = module_path.to_vec();
            nested_path.push(entry.file_name().to_string_lossy().into_owned());
            visit_dir(&path, &nested_path, routes)?;
            continue;
        }

        if path.extension().and_then(|ext| ext.to_str()) == Some("rs") {
            visit_file(&path, module_path, routes)?;
        }
    }

    Ok(())
}

fn visit_file(path: &Path, module_path: &[String], routes: &mut Vec<RpcRoute>) -> Result<()> {
    let file_module_path = file_module_path(path, module_path);
    let source = fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let file = syn::parse_file(&source).with_context(|| format!("parsing {}", path.display()))?;

    for item in &file.items {
        if let Item::Fn(item_fn) = item {
            for route_attr in rocket_route_attrs(item_fn) {
                routes.push(route_from_fn(path, &file_module_path, item_fn, route_attr));
            }
        }
    }

    Ok(())
}

fn file_module_path(path: &Path, module_path: &[String]) -> Vec<String> {
    let stem = path
        .file_stem()
        .and_then(|stem| stem.to_str())
        .unwrap_or_default();

    match stem {
        "mod" | "lib" | "main" => module_path.to_vec(),
        _ => {
            let mut nested = module_path.to_vec();
            nested.push(stem.to_owned());
            nested
        }
    }
}

fn rocket_route_attrs(item_fn: &ItemFn) -> Vec<RocketRouteAttr> {
    item_fn
        .attrs
        .iter()
        .filter_map(|attr| {
            let method = route_method(attr.path().segments.last()?.ident.to_string().as_str())?;
            let args = attr.parse_args::<RocketRouteArgs>().ok()?;
            Some(RocketRouteAttr {
                method: method.to_owned(),
                path: args.path.value(),
                data_param: args.data_param,
            })
        })
        .collect()
}

fn route_method(ident: &str) -> Option<&'static str> {
    match ident {
        "get" => Some("GET"),
        "post" => Some("POST"),
        "put" => Some("PUT"),
        "delete" => Some("DELETE"),
        "patch" => Some("PATCH"),
        _ => None,
    }
}

fn route_from_fn(
    path: &Path,
    module_path: &[String],
    item_fn: &ItemFn,
    route_attr: RocketRouteAttr,
) -> RpcRoute {
    let mut warnings = Vec::new();
    let inputs = route_inputs(item_fn);
    let path_params = discover_path_params(&route_attr.path, &inputs, &mut warnings);
    let body = route_attr
        .data_param
        .as_deref()
        .and_then(|name| inputs.iter().find(|input| input.name == name))
        .and_then(|input| json_inner_type(&input.rust_type));
    let (response, error) = response_and_error(item_fn);
    let auth = auth_for_route(item_fn, &inputs);
    let support = classify_support(
        &inputs,
        response.as_deref(),
        error.as_deref(),
        body.as_deref(),
    );

    if route_attr.data_param.is_some() && body.is_none() {
        warnings.push("data parameter is not a supported Json<T> body".to_owned());
    }

    if response.is_none() && support == RpcRouteSupport::Json {
        warnings.push("response type could not be inferred".to_owned());
    }

    RpcRoute {
        name: item_fn.sig.ident.to_string(),
        module_path: module_path.to_vec(),
        source: path.display().to_string(),
        method: route_attr.method,
        path: route_attr.path,
        data_param: route_attr.data_param,
        path_params,
        body,
        response,
        error,
        auth,
        support,
        warnings,
    }
}

#[derive(Debug)]
struct RouteInput {
    name: String,
    rust_type: String,
}

fn route_inputs(item_fn: &ItemFn) -> Vec<RouteInput> {
    item_fn
        .sig
        .inputs
        .iter()
        .filter_map(|input| {
            let FnArg::Typed(pat_type) = input else {
                return None;
            };
            let Pat::Ident(pat_ident) = pat_type.pat.as_ref() else {
                return None;
            };

            Some(RouteInput {
                name: pat_ident.ident.to_string(),
                rust_type: type_to_string(&pat_type.ty),
            })
        })
        .collect()
}

fn discover_path_params(
    path: &str,
    inputs: &[RouteInput],
    warnings: &mut Vec<String>,
) -> Vec<RpcParam> {
    let mut params = Vec::new();
    for segment in path.split('/') {
        let Some(raw) = segment.strip_prefix('<').and_then(|s| s.strip_suffix('>')) else {
            continue;
        };

        let (name, variadic) = match raw.strip_suffix("..") {
            Some(name) => (name, true),
            None => (raw, false),
        };

        match inputs.iter().find(|input| input.name == name) {
            Some(input) => params.push(RpcParam {
                name: name.to_owned(),
                rust_type: input.rust_type.clone(),
                variadic,
            }),
            None => warnings.push(format!("path parameter `{name}` has no matching argument")),
        }
    }
    params
}

fn response_and_error(item_fn: &ItemFn) -> (Option<String>, Option<String>) {
    let ReturnType::Type(_, ty) = &item_fn.sig.output else {
        return (None, None);
    };

    let output = type_to_string(ty);
    if let Some(inner) = json_inner_type(&output) {
        return (Some(inner), None);
    }

    if let Some((ok, err)) =
        split_result_like(&output, "Result").or_else(|| split_result_like(&output, "ApiResult"))
    {
        return (json_inner_type(&ok).or(Some(ok)), err);
    }

    (None, Some(output))
}

fn split_result_like(output: &str, wrapper: &str) -> Option<(String, Option<String>)> {
    let generic = generic_inner_for_last_segment(output, wrapper)?;
    let parts = split_top_level_commas(&generic);
    match parts.as_slice() {
        [ok] if wrapper == "ApiResult" => Some((ok.to_string(), Some(wrapper.to_owned()))),
        [ok, err] => Some((ok.to_string(), Some(err.to_string()))),
        _ => None,
    }
}

fn auth_for_route(item_fn: &ItemFn, inputs: &[RouteInput]) -> RpcAuth {
    if let Some(auth) = auth_from_requires_auth_attr(item_fn) {
        return auth;
    }

    for input in inputs {
        if type_last_segment(&input.rust_type) == Some("OptionalAuthSession") {
            return RpcAuth::Optional;
        }
    }

    for input in inputs {
        match type_last_segment(&input.rust_type) {
            Some("AuthSession") => return RpcAuth::Required,
            Some("AuthorizedSession") => {
                return RpcAuth::Authorized {
                    policy: generic_inner_for_last_segment(&input.rust_type, "AuthorizedSession"),
                    roles: Vec::new(),
                    permissions: Vec::new(),
                    scopes: Vec::new(),
                    resource: None,
                    mode: AuthMode::All,
                };
            }
            _ => {}
        }
    }

    RpcAuth::None
}

fn auth_from_requires_auth_attr(item_fn: &ItemFn) -> Option<RpcAuth> {
    let attr = item_fn.attrs.iter().find(|attr| {
        attr.path()
            .segments
            .last()
            .is_some_and(|segment| segment.ident == "requires_auth")
    })?;

    let args = attr
        .parse_args_with(Punctuated::<RequiresAuthArg, Token![,]>::parse_terminated)
        .ok()?;
    let mut auth = ParsedRequiresAuth::default();
    for arg in args {
        match arg {
            RequiresAuthArg::Optional => auth.optional = true,
            RequiresAuthArg::Resource(resource) => auth.resource = Some(resource),
            RequiresAuthArg::Claim(claim) => auth.push(claim),
            RequiresAuthArg::Group { mode, claims } => {
                auth.mode = mode;
                for claim in claims {
                    auth.push(claim);
                }
            }
        }
    }

    if auth.optional {
        Some(RpcAuth::Optional)
    } else if auth.has_policy() {
        Some(RpcAuth::Authorized {
            policy: None,
            roles: auth.roles,
            permissions: auth.permissions,
            scopes: auth.scopes,
            resource: auth.resource,
            mode: auth.mode,
        })
    } else {
        Some(RpcAuth::Required)
    }
}

#[derive(Default)]
struct ParsedRequiresAuth {
    optional: bool,
    roles: Vec<String>,
    permissions: Vec<String>,
    scopes: Vec<String>,
    resource: Option<String>,
    mode: AuthMode,
}

impl ParsedRequiresAuth {
    fn push(&mut self, claim: RequiresAuthClaim) {
        match claim {
            RequiresAuthClaim::Role(value) => self.roles.push(value),
            RequiresAuthClaim::Permission(value) => self.permissions.push(value),
            RequiresAuthClaim::Scope(value) => self.scopes.push(value),
        }
    }

    fn has_policy(&self) -> bool {
        !self.roles.is_empty() || !self.permissions.is_empty() || !self.scopes.is_empty()
    }
}

impl Default for AuthMode {
    fn default() -> Self {
        Self::All
    }
}

enum RequiresAuthArg {
    Optional,
    Resource(String),
    Claim(RequiresAuthClaim),
    Group {
        mode: AuthMode,
        claims: Vec<RequiresAuthClaim>,
    },
}

enum RequiresAuthClaim {
    Role(String),
    Permission(String),
    Scope(String),
}

impl Parse for RequiresAuthArg {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let name = input.parse::<syn::Ident>()?;
        match name.to_string().as_str() {
            "optional" => Ok(Self::Optional),
            "resource" => {
                input.parse::<Token![=]>()?;
                Ok(Self::Resource(input.parse::<LitStr>()?.value()))
            }
            "role" | "permission" | "scope" => {
                input.parse::<Token![=]>()?;
                claim_from_name(&name.to_string(), input.parse::<LitStr>()?.value())
                    .map(Self::Claim)
            }
            "any" | "all" => {
                let mode = if name == "any" {
                    AuthMode::Any
                } else {
                    AuthMode::All
                };
                let content;
                syn::parenthesized!(content in input);
                let parsed =
                    Punctuated::<RequiresAuthClaim, Token![,]>::parse_terminated(&content)?;
                Ok(Self::Group {
                    mode,
                    claims: parsed.into_iter().collect(),
                })
            }
            _ => Err(syn::Error::new_spanned(
                name,
                "unsupported requires_auth argument",
            )),
        }
    }
}

impl Parse for RequiresAuthClaim {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let name = input.parse::<syn::Ident>()?;
        input.parse::<Token![=]>()?;
        claim_from_name(&name.to_string(), input.parse::<LitStr>()?.value())
    }
}

fn claim_from_name(name: &str, value: String) -> syn::Result<RequiresAuthClaim> {
    match name {
        "role" => Ok(RequiresAuthClaim::Role(value)),
        "permission" => Ok(RequiresAuthClaim::Permission(value)),
        "scope" => Ok(RequiresAuthClaim::Scope(value)),
        _ => Err(syn::Error::new(
            proc_macro2::Span::call_site(),
            "unsupported requires_auth claim",
        )),
    }
}

fn classify_support(
    inputs: &[RouteInput],
    response: Option<&str>,
    error_or_responder: Option<&str>,
    body: Option<&str>,
) -> RpcRouteSupport {
    if inputs
        .iter()
        .any(|input| is_raw_or_stream_type(&input.rust_type))
        || response.is_some_and(is_raw_or_stream_type)
        || error_or_responder.is_some_and(is_raw_or_stream_type)
    {
        return RpcRouteSupport::Raw;
    }

    if body.is_some() || response.is_some() {
        return RpcRouteSupport::Json;
    }

    RpcRouteSupport::Unsupported
}

fn is_raw_or_stream_type(rust_type: &str) -> bool {
    [
        "ByteStream",
        "WebSocketResponse",
        "WebSocketUpgrade",
        "R2Object",
        "Capped",
        "Status",
        "String",
        "Vec < u8 >",
        "Vec<u8>",
    ]
    .iter()
    .any(|needle| rust_type.contains(needle))
}

fn json_inner_type(rust_type: &str) -> Option<String> {
    generic_inner_for_last_segment(rust_type, "Json")
}

fn generic_inner_for_last_segment(rust_type: &str, segment: &str) -> Option<String> {
    let patterns = [
        format!("{segment} <"),
        format!("{segment}<"),
        format!(":: {segment} <"),
        format!("::{segment}<"),
    ];
    let start = patterns
        .iter()
        .filter_map(|pattern| rust_type.find(pattern).map(|index| index + pattern.len()))
        .next()?;
    let end = matching_generic_end(rust_type, start)?;
    Some(rust_type[start..end].trim().to_owned())
}

fn matching_generic_end(text: &str, start: usize) -> Option<usize> {
    let mut depth = 1usize;
    for (offset, ch) in text[start..].char_indices() {
        match ch {
            '<' => depth += 1,
            '>' => {
                depth -= 1;
                if depth == 0 {
                    return Some(start + offset);
                }
            }
            _ => {}
        }
    }
    None
}

fn split_top_level_commas(text: &str) -> Vec<String> {
    let mut parts = Vec::new();
    let mut depth = 0usize;
    let mut start = 0usize;

    for (index, ch) in text.char_indices() {
        match ch {
            '<' => depth += 1,
            '>' => depth = depth.saturating_sub(1),
            ',' if depth == 0 => {
                parts.push(text[start..index].trim().to_owned());
                start = index + ch.len_utf8();
            }
            _ => {}
        }
    }

    parts.push(text[start..].trim().to_owned());
    parts
}

fn type_last_segment(rust_type: &str) -> Option<&str> {
    let head = rust_type.split('<').next().unwrap_or(rust_type).trim();
    head.split("::").last().map(str::trim)
}

fn strip_angle_binding(value: &str) -> &str {
    value
        .strip_prefix('<')
        .and_then(|value| value.strip_suffix('>'))
        .unwrap_or(value)
}

fn type_to_string(ty: &Type) -> String {
    ty.to_token_stream().to_string()
}

#[allow(dead_code)]
fn _normalize_path(path: PathBuf) -> String {
    path.display().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write(dir: &Path, relative: &str, contents: &str) {
        let path = dir.join(relative);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, contents).unwrap();
    }

    #[test]
    fn discovers_json_routes_and_auth_guards() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "src/tasks/routes.rs",
            r#"
            use comet::cloudflare::D1;
            use comet_auth::{AuthSession, AuthorizedSession};
            use rocket::serde::json::Json;

            pub struct DB;
            pub struct TaskWritePolicy;
            pub struct Task;
            pub struct NewTask;
            pub struct ApiError;
            pub type ApiResult<T> = Result<T, ApiError>;

            #[get("/tasks")]
            pub async fn list_tasks(session: AuthSession, db: D1<DB>) -> ApiResult<Json<Vec<Task>>> {
                todo!()
            }

            #[post("/tasks", data = "<new_task>")]
            pub async fn create_task(new_task: Json<NewTask>, session: AuthSession) -> ApiResult<Json<Task>> {
                todo!()
            }

            #[post("/tasks/<id>/complete")]
            pub async fn complete_task(id: i32, session: AuthorizedSession<TaskWritePolicy>) -> ApiResult<Json<Task>> {
                todo!()
            }
            "#,
        );

        let manifest = discover_manifest(dir.path()).unwrap();

        assert_eq!(manifest.version, MANIFEST_VERSION);
        assert_eq!(manifest.routes.len(), 3);
        assert_eq!(manifest.routes[0].name, "complete_task");
        assert_eq!(manifest.routes[0].path_params[0].name, "id");
        assert_eq!(manifest.routes[0].path_params[0].rust_type, "i32");
        assert_eq!(
            manifest.routes[0].auth,
            RpcAuth::Authorized {
                policy: Some("TaskWritePolicy".to_owned()),
                roles: Vec::new(),
                permissions: Vec::new(),
                scopes: Vec::new(),
                resource: None,
                mode: AuthMode::All,
            }
        );
        assert_eq!(manifest.routes[1].body, Some("NewTask".to_owned()));
        assert_eq!(manifest.routes[1].response, Some("Task".to_owned()));
        assert_eq!(manifest.routes[2].response, Some("Vec < Task >".to_owned()));
        assert_eq!(manifest.routes[2].auth, RpcAuth::Required);
    }

    #[test]
    fn parses_requires_auth_macro_metadata() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "src/demo/routes.rs",
            r#"
            #[comet_auth::requires_auth(any(role = "admin", permission = "tasks:review"), resource = "demo")]
            #[get("/private/reviewer")]
            pub async fn private_reviewer() -> &'static str {
                "reviewer"
            }
            "#,
        );

        let manifest = discover_manifest(dir.path()).unwrap();

        assert_eq!(
            manifest.routes[0].auth,
            RpcAuth::Authorized {
                policy: None,
                roles: vec!["admin".to_owned()],
                permissions: vec!["tasks:review".to_owned()],
                scopes: Vec::new(),
                resource: Some("demo".to_owned()),
                mode: AuthMode::Any,
            }
        );
        assert_eq!(manifest.routes[0].support, RpcRouteSupport::Unsupported);
    }

    #[test]
    fn marks_raw_routes() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "src/assets/routes.rs",
            r#"
            use std::path::PathBuf;
            use rocket::data::Capped;
            use rocket::http::Status;

            #[put("/assets/<key..>", data = "<body>")]
            pub async fn put_asset(key: PathBuf, body: Capped<Vec<u8>>) -> Result<Status, Status> {
                todo!()
            }
            "#,
        );

        let manifest = discover_manifest(dir.path()).unwrap();

        assert_eq!(manifest.routes[0].support, RpcRouteSupport::Raw);
        assert_eq!(manifest.routes[0].path_params[0].name, "key");
        assert!(manifest.routes[0].path_params[0].variadic);
    }

    #[test]
    fn applies_mount_prefixes_from_routes_macro() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "src/app.rs",
            r#"
            use crate::tasks::routes::list_tasks;

            pub fn rocket() {
                rocket::build().mount("/api/v1", routes![list_tasks]);
            }
            "#,
        );
        write(
            dir.path(),
            "src/tasks/routes.rs",
            r#"
            use rocket::serde::json::Json;

            pub struct Task;

            #[get("/tasks")]
            pub async fn list_tasks() -> Json<Vec<Task>> {
                todo!()
            }
            "#,
        );

        let manifest = discover_manifest(dir.path()).unwrap();

        assert_eq!(manifest.routes[0].path, "/api/v1/tasks");
        assert!(manifest.routes[0].warnings.is_empty());
    }

    #[test]
    fn warns_when_route_has_multiple_mount_prefixes() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "src/app.rs",
            r#"
            use crate::tasks::routes::list_tasks;

            pub fn rocket() {
                rocket::build()
                    .mount("/api", routes![list_tasks])
                    .mount("/internal", routes![list_tasks]);
            }
            "#,
        );
        write(
            dir.path(),
            "src/tasks/routes.rs",
            r#"
            use rocket::serde::json::Json;

            pub struct Task;

            #[get("/tasks")]
            pub async fn list_tasks() -> Json<Vec<Task>> {
                todo!()
            }
            "#,
        );

        let manifest = discover_manifest(dir.path()).unwrap();

        assert_eq!(manifest.routes[0].path, "/tasks");
        assert!(
            manifest.routes[0]
                .warnings
                .iter()
                .any(|warning| warning.contains("multiple prefixes"))
        );
    }

    #[test]
    fn generates_typescript_client_for_json_routes() {
        let manifest = RpcManifest {
            version: MANIFEST_VERSION,
            routes: vec![
                RpcRoute {
                    name: "get_task".to_owned(),
                    module_path: vec!["tasks".to_owned(), "routes".to_owned()],
                    source: "src/tasks/routes.rs".to_owned(),
                    method: "GET".to_owned(),
                    path: "/api/tasks/<id>".to_owned(),
                    data_param: None,
                    path_params: vec![RpcParam {
                        name: "id".to_owned(),
                        rust_type: "i32".to_owned(),
                        variadic: false,
                    }],
                    body: None,
                    response: Some("Task".to_owned()),
                    error: None,
                    auth: RpcAuth::Required,
                    support: RpcRouteSupport::Json,
                    warnings: Vec::new(),
                },
                RpcRoute {
                    name: "put_asset".to_owned(),
                    module_path: vec!["assets".to_owned(), "routes".to_owned()],
                    source: "src/assets/routes.rs".to_owned(),
                    method: "PUT".to_owned(),
                    path: "/assets/<key..>".to_owned(),
                    data_param: Some("body".to_owned()),
                    path_params: vec![RpcParam {
                        name: "key".to_owned(),
                        rust_type: "PathBuf".to_owned(),
                        variadic: true,
                    }],
                    body: None,
                    response: None,
                    error: None,
                    auth: RpcAuth::None,
                    support: RpcRouteSupport::Raw,
                    warnings: Vec::new(),
                },
            ],
        };

        let mut types = TsTypes::default();
        types.models.insert(
            "Task".to_owned(),
            TsModel {
                name: "Task".to_owned(),
                fields: vec![TsModelField {
                    name: "id".to_owned(),
                    rust_type: "i32".to_owned(),
                    ts_type: "number".to_owned(),
                    optional: false,
                }],
            },
        );

        let ts = generate_typescript_client_with_types(&manifest, &types);

        assert!(ts.contains("export interface Task {\n  id: number;\n}"));
        assert!(ts.contains("async getTask(id: number): Promise<Task>"));
        assert!(ts.contains("`/api/tasks/${encodePathValue(id)}`"));
        assert!(ts.contains("this.request<Task>(\"GET\""));
        assert!(!ts.contains("putAsset"));
    }

    #[test]
    fn discovers_typescript_models_for_used_structs() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "src/tasks/routes.rs",
            r#"
            use rocket::serde::json::Json;

            #[derive(serde::Serialize)]
            pub struct Task {
                pub id: i32,
                #[serde(rename = "taskTitle")]
                pub title: String,
                pub done: bool,
                pub archived_at: Option<String>,
                pub status: TaskStatus,
                private_note: String,
            }

            #[derive(serde::Serialize)]
            #[serde(rename_all = "snake_case")]
            pub enum TaskStatus {
                InProgress,
                Done,
                #[serde(rename = "blocked_custom")]
                Blocked,
            }

            #[get("/tasks/<id>")]
            pub async fn get_task(id: i32) -> Json<Task> {
                todo!()
            }
            "#,
        );

        let manifest = discover_manifest(dir.path()).unwrap();
        let types = discover_typescript_types(dir.path(), &manifest).unwrap();
        let ts = generate_typescript_client_with_types(&manifest, &types);

        assert!(ts.contains("export interface Task {"));
        assert!(ts.contains("  id: number;"));
        assert!(ts.contains("  taskTitle: string;"));
        assert!(ts.contains("  done: boolean;"));
        assert!(ts.contains("  archived_at?: string | null;"));
        assert!(ts.contains("  status: TaskStatus;"));
        assert!(
            ts.contains(
                "export type TaskStatus = \"in_progress\" | \"done\" | \"blocked_custom\";"
            )
        );
        assert!(!ts.contains("private_note"));
    }

    #[test]
    fn generates_dart_client_for_json_routes() {
        let manifest = RpcManifest {
            version: MANIFEST_VERSION,
            routes: vec![RpcRoute {
                name: "create_task".to_owned(),
                module_path: vec!["tasks".to_owned(), "routes".to_owned()],
                source: "src/tasks/routes.rs".to_owned(),
                method: "POST".to_owned(),
                path: "/tasks".to_owned(),
                data_param: Some("new_task".to_owned()),
                path_params: Vec::new(),
                body: Some("NewTask".to_owned()),
                response: Some("Task".to_owned()),
                error: None,
                auth: RpcAuth::Required,
                support: RpcRouteSupport::Json,
                warnings: Vec::new(),
            }],
        };
        let mut types = TsTypes::default();
        types.models.insert(
            "NewTask".to_owned(),
            TsModel {
                name: "NewTask".to_owned(),
                fields: vec![TsModelField {
                    name: "title".to_owned(),
                    rust_type: "String".to_owned(),
                    ts_type: "string".to_owned(),
                    optional: false,
                }],
            },
        );
        types.models.insert(
            "Task".to_owned(),
            TsModel {
                name: "Task".to_owned(),
                fields: vec![
                    TsModelField {
                        name: "id".to_owned(),
                        rust_type: "i32".to_owned(),
                        ts_type: "number".to_owned(),
                        optional: false,
                    },
                    TsModelField {
                        name: "status".to_owned(),
                        rust_type: "TaskStatus".to_owned(),
                        ts_type: "TaskStatus".to_owned(),
                        optional: false,
                    },
                ],
            },
        );
        types.enums.insert(
            "TaskStatus".to_owned(),
            TsEnum {
                name: "TaskStatus".to_owned(),
                variants: vec!["in_progress".to_owned(), "done".to_owned()],
            },
        );

        let dart = generate_dart_client_with_types(&manifest, &types);

        assert!(dart.contains("class NewTask {"));
        assert!(dart.contains("final String title;"));
        assert!(dart.contains("enum TaskStatus {"));
        assert!(dart.contains("in_progress"));
        assert!(dart.contains("Future<Task> createTask(NewTask new_task) async"));
        assert!(dart.contains("return _request<Task>('POST', '/tasks', new_task, true"));
        assert!(dart.contains("Task.fromJson(value)"));
    }

    #[test]
    fn resolves_required_authorization_policy_from_target_crate() {
        let dir = tempfile::tempdir().unwrap();
        let workspace = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .to_path_buf();
        let comet_auth_path = workspace.join("comet-auth");
        let rocket_path = workspace.join("vendor/rocket/core/lib");

        write(
            dir.path(),
            "Cargo.toml",
            &format!(
                r#"
                [package]
                name = "rpc-policy-fixture"
                version = "0.0.0"
                edition = "2021"

                [dependencies]
                comet-auth = {{ path = "{}", default-features = false }}
                rocket = {{ path = "{}", default-features = false, features = ["json"] }}
                "#,
                comet_auth_path.display(),
                rocket_path.display(),
            ),
        );
        write(dir.path(), "src/lib.rs", "pub mod routes;\n");
        write(
            dir.path(),
            "src/routes.rs",
            r#"
            use comet_auth::{
                AuthorizationMode, AuthorizationRequirement, AuthorizedSession,
                RequiredAuthorization,
            };

            pub struct WritePolicy;

            impl RequiredAuthorization for WritePolicy {
                const REQUIREMENT: AuthorizationRequirement =
                    AuthorizationRequirement::with_mode_and_resource(
                        AuthorizationMode::Any,
                        &["admin"],
                        &["tasks:write"],
                        &["tasks:review"],
                        Some("tasks"),
                    );
            }

            #[rocket::post("/write")]
            pub async fn write(_session: AuthorizedSession<WritePolicy>) -> &'static str {
                "ok"
            }
            "#,
        );

        let manifest = discover_manifest(dir.path()).unwrap();
        let RpcAuth::Authorized {
            roles,
            permissions,
            scopes,
            resource,
            mode,
            ..
        } = &manifest.routes[0].auth
        else {
            panic!("expected authorized route");
        };

        assert_eq!(roles, &vec!["admin".to_owned()]);
        assert_eq!(permissions, &vec!["tasks:write".to_owned()]);
        assert_eq!(scopes, &vec!["tasks:review".to_owned()]);
        assert_eq!(resource, &Some("tasks".to_owned()));
        assert_eq!(mode, &AuthMode::Any);
    }
}
